[package]
name = "idempotency-server"
version = "0.1.0"
edition = "2024"



[dependencies]
libsql = "0.9.14"
serde = "1.0.219"
tokio = "1.46.1"
prost = "0.11"
tonic = "0.9"

[build-dependencies]
tonic-build = "0.9"