@startuml
actor "Worker A" as A
actor "Worker B" as B
participant "Workflow Engine" as E

== 1. Workflow Started by Worker A ==
A -> E : [1] Start Workflow
E -> A : [2] Generate Fencing Token A1

note right of A
From now on, Worker A includes\nfencing token A1 in each request
end note

A -> E : [3] Request lease for Task 1 + check execution [Token A1]
E -> A : [4] Not executed\nLease granted

A -> A : [5] Execute Task 1

== 2. Meanwhile: Worker B Starts Same Workflow ==
B -> E : [6] Start Workflow
E -> B : [7] Generate Fencing Token B1

B -> E : [8] Request lease for Task 1 + check execution [Token B1]
E -> B : [9] Task already leased\nWait X ms

loop [10] Retry every X/10 ms
    B -> E : Request lease for Task 1 + check execution [Token B1]
end

== 3. Worker A Finishes Execution ==
alt [11] Task execution FAILED
    A -> E : [12] Release Lease [Token A1]
    A -> A : [13] Stop
end

alt [14] Task execution SUCCEEDED
    loop [15] Up to 10 times
        alt [16] Checkpoint Success
        break
            E -> A : [17] Acknowledge Checkpoint
        end
    end

end
    alt [18] All retries failed AND rollback provided
        A -> A : [19] Rollback
    end
  A -> A : [20] Abort due to outdated fencing token

== 4. Back to Worker B ==
B -> E : Request lease for Task 1 + check execution [Token B1]
alt [21] Worker's A Checkpoint was Successful
    E -> B : 22 Return checkpoint result
    B -> B : [23] Skip execution
end
alt [24] No Checkpoint was done
    B -> B : [25] Execute Task 1
end
@enduml
